# Generated by Django 4.1.1 on 2022-09-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_pessoas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='pessoas',
            new_name='pessoa',
        ),
    ]
